import {
  I_HOME,
  I_HOME_FILLED,
  I_WATCH,
  I_WATCH_FILLED,
  I_MARKETPLACE,
  I_MARKETPLACE_FILLED,
  I_GROUP,
  I_GROUP_FILLED,
  I_GAMING,
  I_GAMING_FILLED,
} from "../../assets/images/svg";
import { iconSecondaryColor, btnPrimaryBgColor } from "../../styles/style";

export const TEXTS = {
  texSearch: "Tìm kiếm trên Facebook",
};

export const MENU_INFO = [
  {
    size: 28,
    color: iconSecondaryColor,
    colorFilled: btnPrimaryBgColor,
    icon: I_HOME,
    iconFilled: I_HOME_FILLED,
    title: "Home",
    wrapClassName: "home",
    iconClassName: "home-icon",
    isActive: "active",
    path: "/",
  },
  {
    size: 28,
    color: iconSecondaryColor,
    colorFilled: btnPrimaryBgColor,
    icon: I_WATCH,
    iconFilled: I_WATCH_FILLED,
    title: "Watch",
    wrapClassName: "watch",
    className: "watch-icon",
    isActive: "de-active",
    path: "/watch",
  },
  {
    size: 28,
    color: iconSecondaryColor,
    colorFilled: btnPrimaryBgColor,
    icon: I_MARKETPLACE,
    iconFilled: I_MARKETPLACE_FILLED,
    title: "Market Place",
    wrapClassName: "marketplace",
    className: "marketplace-icon",
    isActive: "de-active",
    path: "/marketplace",
  },
  {
    size: 28,
    color: iconSecondaryColor,
    colorFilled: btnPrimaryBgColor,
    icon: I_GROUP,
    iconFilled: I_GROUP_FILLED,
    title: "Group",
    wrapClassName: "group",
    className: "group-icon",
    isActive: "de-active",
    path: "/group",
  },
  {
    size: 28,
    color: iconSecondaryColor,
    colorFilled: btnPrimaryBgColor,
    icon: I_GAMING,
    iconFilled: I_GAMING_FILLED,
    title: "Gaming",
    wrapClassName: "gaming",
    className: "gaming-icon",
    isActive: "de-active",
    path: "/gaming",
  },
];
